on:
  workflow_call:
    inputs:
      cf_environment:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        type: string
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --env ${{ inputs.cf_environment }} --branch ${{ github.ref_name }} --project-name=clean artifact/cloudflare
