name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment in github to target
        type: string
        required: true
      cf_environment:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        type: string
        required: true
        default: 'dev'

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --env ${{ inputs.cf_environment }} --branch ${{ github.ref_name }} --project-name=clean artifact/cloudflare
